---

- name: Apt | Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - fail2ban
    - iptables
    - iptables-persistent

- name: Template | Add iptables
  ansible.builtin.template:
    src: rules.v4
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Handler | Apply iptables

...
