---

- name: Handler | Apply iptables
  ansible.builtin.shell: iptables-restore < /etc/iptables/rules.v4
  args:
    executable: /bin/bash
  changed_when: false

- name: Handler | Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  changed_when: false

...
