---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:
    iptables:
      router: false
      pingables:
      - host: all_hosts
        ip: 0.0.0.0
      chains:
      - name: HTTP
        comment: "http"
        protocol: tcp  # tcp/icmp/udp
        ports:
        - 80
        - 443

  tasks:
  - name: Include andrelohmann.iptables
    ansible.builtin.include_role:
      name: "andrelohmann.iptables"
...
